### ISSUE TITLE
Weasyprint dependency causes error

### ISSUE THREAD

**Issue by printfinn** [iSOLveIT/sphinx-pdf-generate#4]
Hi Randy, 

Weasyprint bumped their version from 59.0 to 60.0 yesterday, it broke our build process.

In my local environment, generating PDF works, because I was using the local v59.0 Weasyprint.

I found our Github action fails when converting the AIO-CM4-101 product (pdfgen_debug_target = "PCs/Pi/AIO/Manuals/Hardware/CS12800RA4101A.rst"), I looked at the trace and found it's caused by the Weasyprint dependency.

As soon as I upgrade my local Weasyprint from v59.0 to v60.0, the same error occurs when I generate PDF on my Mac, like the one I see in our Github action.

This is the failing build: https://github.com/Chipsee/Documentation/actions/runs/6310555395/job/17132754163

I think we can pin the Weasyprint version to v59.0 to fix this problem, or maybe you want to investigate what's happening and maybe change this sphinx-pdf-generate repo. (Or maybe Weasyprint can fix their bug, and we just wait for them to fix it).

**Comment by printfinn** [comment]
Hi Randy, don't bother it, I managed to edit the rst file and made it work again.

I split and conquered the rst file, and found a small paragraph describing power input, still don't know which character caused the decoding bug though, but I edited the paragraph, changed some "/" to "-", and it works now!

Other documents are OK, they are not affected by the new Weasyprint version.

**Comment by iSOLveIT** [comment]
Thanks for the issue and fix.
