### ISSUE TITLE
Fix Weasyprint to 60.0

### ISSUE THREAD

**Issue by printfinn** [iSOLveIT/sphinx-pdf-generate#5]
As weasyprint upgrades to 61.0, every PDF generates only the cover page now.

I've tested you can fix weasyprint==60.0 to fix this issue, then this library will work as usual, and generates all pages of the PDF.

**Comment by iSOLveIT** [comment]
Hi @printfinn, 
Thank you for the issue and solution. I will fix the allowed weasyprint version to 60.0 and check if we can improve the code to work with weasyprint==61.0.
