### ISSUE TITLE
Pinning to weasyprint version 60.0 breaks sphinx-pdf-generate

### ISSUE THREAD

**Issue by BFH-hga3** [iSOLveIT/sphinx-pdf-generate#6]
The fixed version of weasyprint breaks because the pypdf changed how to create a PDF object (ctor interface). More recent versions of weasyprint respect the change. If we use a fixed version of weasyprint without fixing the version of dependant libraries the function of sphinx-pdf-generate may break. This is exactly what happens with pypdf==4.3.0 and weasyprint== >=60.0, <61.0.

Use weasyprint = ">=62.0" instead.

**Comment by iSOLveIT** [comment]
Thank you for the issue and the PR to fix it. I will review it ASAP.
